### ISSUE TITLE
Send data to a LEGO Hub

### ISSUE THREAD

**Issue by gotfredsen** [NStrijbosch/RevEng-hub2hub-word-blocks#2]
Great help. Managed to read data using am ESP32. Thank you!

Have you been able to send data to a LEGO Hub.
I have been able to advertise the exact same data, and my ESP32 sees it as the same, except for two details.
My data have a name "ESP32", which I so far haven't been able to get rid of. And my ESP32 have another address. But the advertisement data are the same.

I must be missing something, like some flags, or payload or scan response, something. Any help ... any luck?

**Comment by NStrijbosch** [comment]
Yes I have been able to both send and receive from other devices. In my case not ESP32. 

What you need is to be able to set the full advertising data. For example sending data with an iPhone to a MINDSTORMS hub is also not possible since apple restricts app developers to not change the manufacturer ID which needs to be the LEGO ID.

Is this your issue as well? I expect there should be a mode on the ESP32 that allows to change this.

Do you have 2 ESP32 boards? What is the exact message received on one ESP32 board if you send with the other one? And how is it different to the message of a MINDSTORMS hub?

**Comment by gotfredsen** [comment]
Yes, I have many ESP32 all kinds including ESP32C3 (BLE 5.0).

Sending from a LEGO hub and from an ESP32 to another ESP32, I get this:
```
Name: , Address: b0:b1:13:9b:8b:d7, manufacturer data: 97035f06d2e4fb61626364
Name: ESP32, Address: ec:94:cb:72:ed:ea, manufacturer data: 9703e606d2e4fb61626364, txPower: 3
```
Top line from LEGO Spike Hub, bottom from ESP32.
Here aligned for ease of reading:
```
Name:      , Address: b0:b1:13:9b:8b:d7, manufacturer data: 97035f06d2e4fb61626364
Name: ESP32, Address: ec:94:cb:72:ed:ea, manufacturer data: 9703e606d2e4fb61626364, txPower: 3
```
As you can see, it is only the message number that is different. The message ID is "signal111" and I have verified that I got the right CRC32, but also send it from the hub to the ESP32 to make sure.

Also the LEGO ID is correct in the manufacturer data. I haven't tried to change the address to a look alike address. There are also flags, etc that can be set, which I haven't.

Do you by any chance have a piece of working code, just a cut out of the source with the action ... in any programming language? That could help.

**Comment by NStrijbosch** [comment]
A clear. I guess the fact that you have the name and the tx power leads to the MINDSTORMS hub not recognizing the message.

**Comment by NStrijbosch** [comment]
I think what you need is to be able to set the RAW advertising data, i.e., set each bit and not only the manufacturer data. In micropython that can be done using: https://docs.micropython.org/en/latest/library/bluetooth.html#broadcaster-role-advertiser

**Comment by gotfredsen** [comment]
I can send all those data in the ESP32 as well:
(interval_us, adv_data=None, *, resp_data=None, connectable=True)

- Interval in uS
- Adv_data, which I am sending now
- Scan Response data (resp_data), which is typically the same, but I tried with and without.
- And a flag for connectable, also set false, true, and not set.

...but I don't know what those (other than adv_data) should be set to.

**Comment by NStrijbosch** [comment]
Can you set the adv_type? I remember now that when I was implementing this in pybricks on the technic hub I could not set it to the correct advertising type and hence the MINDSTORMS hub would not recognize the data correct. The correct advertising type  should be ADV_SCAN_IND.

I hope that insight helps?

**Comment by gotfredsen** [comment]
Ok,
I finally got it to work:

- Build a record similar to the one showed in this repository
- Remember to change the message number, LEGO only responds to the first unique record
- Don't set any flags
- Make a ScanResponse with same content as the AdvertisementData
- Set AdvertisementType to ADV_NONCONN_IND


@NStrijbosch, thanks for your insights
